services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env.production
    volumes:
      - /data:/data
    ports:
      - "3000:3000"
    depends_on:
      - redis

  workers:
    build:
      context: .
      dockerfile: Dockerfile.workers
    restart: unless-stopped
    env_file: .env.production
    volumes:
      - /data:/data
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --save "" --loglevel warning
